name: 04 - Using Actions
on:
    push:
jobs:
    build:
         runs-on: ubuntu-latest
         steps:
            - name: Checkout Code
              uses: actions/checkout@v7
            - name: Setup Node
              uses: actions/setup-node@v7
              with:
                node-version: '24.x'
            - name: Install Dependencies
              working-directory: 04-using-actions
              run: npm ci           
            - name: check for current path 
              run: ls -ltrh