name: 06 - Contexts
on:
    push:
    workflow_dispatch:
jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps: 
           - name: "Display Information"
             run: |
                 echo "Event name: {{github.event}}"
                 echo "Ref: {{ github.ref }}"
                 echo "SHA: {{ github.sha }}"
                 echo "ACTOR: {{ github.actor }}"
                 echo "ACTION: {{ github.action }}"
                 echo "Workflow: {{ github.workflow }}"
                 echo "Run ID: {{ github.run_id}}"
                 echo "Run number: {{ github.run_number}}"
